credentials:
  usernames:
    user1:
      email: user1@example.com
      name: Тестовый Пользователь 1
      password: '$2b$12$80jGArz322gKj8D./v7kK.1z3a/j.L5.B/C6.E7.H8'
    user2:
      email: user2@example.com
      name: Тестовый Пользователь 2
      password: '$2b$12$Z.A1.B2.C3.D4.E5.F6.G7.H8.I9.J0.K1.L2.M3.N'
cookies:
  cookie_name: my_finance_app_cookie
  key: a_very_secret_key_12345
  expiry_days: 30
preauthorized:
  emails: []
