credentials:
  usernames:
    prockosha:
      email: prockosha97@gmail.com
      name: Игорь Прокофьев
      password: $2b$12$rNgGchlqhBks3wvShIJDGe4QThTCx.W1X2rxjR0eTPPI7.5kMuBVC
    Lesha_Petrov:
      email: a9petrov9@gmail.com
      name: Алексей Петров
      password: $2b$12$VExy0b3Mnv4vInIQvk1j7exgYpJm4GKIpCJ7wJxQ7b1PuHiMf6bd.
cookie:
  name: finance_app_cookie
  key: your_random_key_here_123456789  # измени на случайную строку 16+ символов
  expiry_days: 30
# УБРАТЬ эту секцию полностью ↓
# preauthorized:
#   emails: []